=== plataforma-tierra/data-models/AgriFertilize/schema.json
{
  "$id": "https://example.com/schema/AgriFertilize",
  "$schema": "http://json-schema.org/schema#",
  "$schemaVersion": "0.0.1",
  "title": "AgriFertilize Schema",
  "description": "Schema for AgriFertilize entity. To fertilize land means to improve its quality in order to make plants grow well on it, by spreading solid animal waste or a chemical mixture on it.",
  "type": "object",
  "derivedFrom": "",
  "license": "https://opensource.org/licenses/MIT",
  "modelTags": "Agrifood, AgriFertilize",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for the AgriFertilize entity."
    },
    "type": {
      "type": "string",
      "description": "Property. NGSI Entity Type. It has to be AgriFertilize.",
      "enum": ["AgriFertilize"]
    },
    "dateCreated": {
      "type": "string",
      "format": "date-time",
      "description": "Property. The date and time when the entity was created."
    },
    "dateModified": {
      "type": "string",
      "format": "date-time",
      "description": "Property. The date and time when the entity was last modified."
    },
    "dose": {
      "type": "number",
      "description": "Property. Fertilizer dose administered."
    },
    "enddate": {
      "type": "string",
      "description": "Property. Final date of fertilizer process. This field can be empty."
    },
    "inidate": {
      "type": "string",
      "description": "Property. The start date of the fertilization process."
    },
    "measure": {
      "type": "object",
      "description": "Property. Details of the measure.",
      "properties": {
        "detail": {
          "type": "string",
          "description": "Property. Notes about the measurement."
        },
        "id": {
          "type": "string",
          "description": "Property. Identifier of the measure."
        },
        "name": {
          "type": "string",
          "description": "Property. Name assigned to the measure."
        },
        "prior": {
          "type": "string",
          "description": "Property. Level of importance of the measure. Available values ​​are between 0 (priority) and 10 (least priority)."
        },
        "type": {
          "type": "string",
          "description": "Property. Type of the measure."
        },
        "code": {
          "type": "number",
          "description": "Property. Ministry code assigned to the measure."
        },
        "symbol": {
          "type": "string",
          "description": "Property. Symbol assigned to the measure."
        }
      }
    },
    "name": {
      "type": "string",
      "description": "Property. Name of the AgriFertilize entity."
    },
    "subtype": {
      "type": "object",
      "description": "Property. Subtype details of the AgriFertilize entity.",
      "properties": {
        "aacm": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "description": "Property. Array of aacm objects associated with the subtype."
        },
        "accm": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "description": "Property. Information about fertilizer type acids."
        },
        "check": {
          "type": "number",
          "description": "Property. Check value associated with the subtype."
        },
        "code": {
          "type": "string",
          "description": "Property. Code of the subtype."
        },
        "comp": {
          "type": "object",
          "description": "Property. Details of the company associated with the subtype.",
          "properties": {
            "id": {
              "type": "number",
              "description": "Property. Identifier of the company."
            },
            "name": {
              "type": "string",
              "description": "Property. Name of the company."
            },
            "nif": {
              "type": "string",
              "description": "Property. NIF of the company."
            },
            "type": {
              "type": "string",
              "description": "Property. Type of the company."
            }
          }
        },
        "hecm": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "description": "Property. Information on heavy metals of the fertilizer type."
        },
        "id": {
          "type": "number",
          "description": "Property. Identifier of the subtype."
        },
        "macm": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "description": "Property. Information on other macronutrients of the fertilizer type."
        },
        "manure": {
          "type": ["null", "string"],
          "description": "Property. Manure details, if any."
        },
        "matdet": {
          "type": ["null", "string"],
          "description": "Property. Material fertilize detail, if any."
        },
        "material": {
          "type": "object",
          "description": "Property. Material details associated with the subtype.",
          "properties": {
            "id": {
              "type": "number",
              "description": "Property. Identifier of the material."
            },
            "name": {
              "type": "string",
              "description": "Property. Name of the material."
            },
            "type": {
              "type": "string",
              "description": "Property. Type of the material."
            }
          }
        },
        "metadata": {
          "type": "array",
          "description": "Property. Array of metadata objects associated with the subtype.",
          "items": {
            "type": "object",
            "properties": {
              "date": {
                "type": "string",
                "format": "date-time",
                "description": "Property. Date associated with the metadata."
              },
              "type": {
                "type": "string",
                "description": "Property. Type of metadata."
              },
              "user": {
                "type": "object",
                "description": "Property. User details associated with the metadata.",
                "properties": {
                  "email": {
                    "type": "string",
                    "description": "Property. Email of the user."
                  },
                  "id": {
                    "type": "string",
                    "description": "Property. Identifier of the user."
                  },
                  "loginname": {
                    "type": "string",
                    "description": "Property. Login name of the user."
                  },
                  "name": {
                    "type": "string",
                    "description": "Property. Name of the user."
                  },
                  "nif": {
                    "type": "string",
                    "description": "Property. NIF of the user."
                  },
                  "surname": {
                    "type": "string",
                    "description": "Property. Surname of the user."
                  },
                  "type": {
                    "type": "string",
                    "description": "Property. Type of the user."
                  }
                }
              }
            }
          }
        },
        "micm": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "description": "Property. Array of micm objects associated with the subtype."
        },
        "mmcm": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "number",
                "description": "Property. Identifier of mmcm."
              },
              "value": {
                "type": "number",
                "description": "Property. This field contains the value associated to the mmcm."
              },
              "subtype": {
                "type": "object",
                "description": "Property. Subtype details of mmcm.",
                "properties": {
                  "code": {
                    "type": "number",
                    "description": "Property. Code of the mmcm subtype."
                  },
                  "id": {
                    "type": "number",
                    "description": "Property. Identifier of the mmcm subtype."
                  },
                  "name": {
                    "type": "string",
                    "description": "Property. Name of the mmcm subtype."
                  },
                  "subtype": {
                    "type": "object",
                    "description": "Property. Nested subtype details of mmcm.",
                    "properties": {
                      "id": {
                        "type": "number",
                        "description": "Property. Identifier of the nested mmcm subtype."
                      },
                      "name": {
                        "type": "string",
                        "description": "Property. Name of the nested mmcm subtype."
                      },
                      "type": {
                        "type": "string",
                        "description": "Property. Type of the nested mmcm subtype."
                      }
                    }
                  },
                  "symbol": {
                    "type": "string",
                    "description": "Property. Symbol of the mmcm subtype."
                  },
                  "type": {
                    "type": "string",
                    "description": "Property. Type of the mmcm subtype."
                  }
                }
              }
            }
          },
          "description": "Property. Array of mmcm objects associated with the subtype."
        },
        "name": {
          "type": "string",
          "description": "Property. Name of the subtype."
        },
        "notes": {
          "type": "string",
          "description": "Property. Notes associated with the subtype."
        },
        "subcode": {
          "type": "string",
          "description": "Property. Subcode of the subtype."
        },
        "symbol": {
          "type": "string",
          "description": "Property. Symbol of the subtype."
        }
      }
    },
    "target": {
      "type": "string",
      "description": "Property. Target details for the AgriFertilize entity."
    },
    "typsoil": {
      "type": "string",
      "description": "Property. Type of soil associated with the AgriFertilize entity."
    },
    "bill": {
      "type": "string",
      "description": "Property. Invoice or delivery note number."
    },
    "detail": {
      "type": "string",
      "description": "Property. User notes on administered fertilizer."
    },   
    "idcp": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Property.  IDs of the CropSigpac on which the fertilizer is applied in the campaign."
    },
    "machine": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "description": "Property.  Information on the machinery assigned to the application of the fertilizer as well as information on its hygiene."
    },
    "maf": {
      "type": "object",
      "description": "Property. Details of the MAF.",
      "properties": {
        "id": {
          "type": "string",
          "description": "Property. Identifier of the MAF."
        },
        "name": {
          "type": "string",
          "description": "Property. Name of the MAF."
        },
        "type": {
          "type": "string",
          "description": "Property. Type of the MAF."
        }
      }
    },    
    "msoup": {
      "type": "object",
      "description": "Property. Details of the MSOUP.",
      "properties": {
        "detail": {
          "type": "string",
          "description": "Property. Details of the msoup."
        },
        "id": {
          "type": "string",
          "description": "Property. Identifier of the msoup."
        },
        "name": {
          "type": "string",
          "description": "Property. Name of the msoup."
        },
        "prior": {
          "type": "string",
          "description": "Property. Prior details of the msoup."
        },
        "type": {
          "type": "string",
          "description": "Property. Type of the msoup."
        },
        "code": {
          "type": "number",
          "description": "Property. Type of the msoup."
        },
        "symbol": {
          "type": "string",
          "description": "Property. Type of the msoup."
        }
      }
    },
    "mud": {
      "type": "number",
      "description": "Property. Indicates whether sewage sludge application document has been used or not."
    },
    "plan": {
      "type": ["null", "string"],
      "description": "Property. Information about the subscriber plans that are part of the campaign."
    },
    "r10": {
      "type": "string",
      "description": "Property. Waste authorization number R10."
    },
    "soup": {
      "type": "number",
      "description": "Property. Final soup amount administered."
    },
    "taf": {
      "type": "object",
      "description": "Property. Details of the TAF.",
      "properties": {
        "id": {
          "type": "string",
          "description": "Property. Identifier of the TAF."
        },
        "name": {
          "type": "string",
          "description": "Property. Name of the TAF."
        },
        "type": {
          "type": "string",
          "description": "Property. Type of the TAF."
        }
      }
    },
    "tgp": {
      "type": "array",
      "items": {
        "type": "object"
      },
      "description": "Property.  Information on good practices of fertilizer applied in the campaign."
    },
    "tmi": {
      "type": "object",
      "description": "Property. Details of the TMI.",
      "properties": {
        "id": {
          "type": "string",
          "description": "Property. Identifier of the TMI."
        },
        "name": {
          "type": "string",
          "description": "Property. Name of the TMI."
        },
        "type": {
          "type": "string",
          "description": "Property. Type of the TMI."
        }
      }
    }
  },
  "required": ["id", "type"]
}

=== plataforma-tierra/data-models/AgriFertilize/base/example.json
{
    "id": "urn:ngsi-ld:AgriFertilize:1",
    "type": "AgriFertilize",
    "dateCreated": "30-05-2024 09:14:44",
    "dateModified": "30-05-2024 09:14:44",
    "name": "",
    "subtype": {
        "type": "TypeFertilize",
        "id": 1339,
        "code": "F0002478/2025",
        "name": "Abono Organico Npk (Ca) 1,5-1-2 (2) Mezcla De Origen Animal Y Vegetal Sirlepur",
        "mmcm": [{
            "type": "CM",
            "id": 10000,
            "subtype": {
                "type": "TCM",
                "id": 1,
                "subtype": {
                    "type": "SCM",
                    "id": 1,
                    "name": "Macronutriente principal"
                },
                "code": 1,
                "name": "Nitrógeno total",
                "symbol": "% N total"
            },
            "value": 1.5
        }, {
            "type": "CM",
            "id": 10001,
            "subtype": {
                "type": "TCM",
                "id": 6,
                "subtype": {
                    "type": "SCM",
                    "id": 1,
                    "name": "Macronutriente principal"
                },
                "code": 6,
                "name": "Óxido de fósforo total",
                "symbol": "% P2O5 total"
            },
            "value": 1
        }, {
            "type": "CM",
            "id": 10002,
            "subtype": {
                "type": "TCM",
                "id": 9,
                "subtype": {
                    "type": "SCM",
                    "id": 1,
                    "name": "Macronutriente principal"
                },
                "code": 9,
                "name": "Óxido de potasio",
                "symbol": "% K2O total"
            },
            "value": 2
        }],
        "macm": [],
        "hecm": [],
        "micm": [],
        "accm": [],
        "aacm": [],
        "otcm": [],
        "comp": {
            "type": "Company",
            "id": 269,
            "name": "Organicos Pedrin, S.l",
            "nif": ""
        },
        "manure": null,
        "material": {
            "type": "TMF",
            "id": 15,
            "name": "Productos fertilizantes: abonos orgánicos"
        },
        "matdet": null,
        "provider": "",
        "nif": "",
        "check": 0,
        "metadata": [{
            "type": "Create",
            "user": {
                "type": "UserMetadata",
                "id": "1",
                "loginname": "sistema",
                "email": "",
                "name": "Sistema",
                "surname": "",
                "nif": ""
            },
            "date": "09-02-2024 15:48:46"
        }],
        "reviewed": "1"
    },
    "inidate": "30-05-2024 09:14:44",
    "enddate": "",
    "dose": 10,
    "measure": {
        "type": "Measure",
        "id": "501",
        "subtype": {
            "type": "TypeMeasure",
            "id": "6",
            "name": "Fertilizante"
        },
        "code": 17,
        "name": "Kilogramo por hectárea",
        "symbol": "kg/ha",
        "prior": "1",
        "detail": ""
    },
    "soup": 1000,
    "msoup": {
        "type": "Measure",
        "id": "514",
        "subtype": {
            "type": "TypeMeasure",
            "id": "6",
            "name": "Fertilizante"
        },
        "code": 4,
        "name": "Litro",
        "symbol": "l",
        "prior": "3",
        "detail": ""
    },
    "r10": "",
    "mud": 0,
    "bill": "",
    "plan": null,
    "taf": {
        "type": "TAF",
        "id": "1",
        "name": "Abonado de fondo"
    },
    "maf": {
        "type": "MAF",
        "id": "1",
        "name": "Esparcido general"
    },
    "tmi": {
        "type": "TMI",
        "id": "1",
        "name": "Sin especificar",
        "acronym": ""
    },
    "tgp": [],
    "machine": [],
    "detail": "",
    "idcp": ["13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39"]
}
